### ISSUE TITLE
Release to Melodic and ROS2?

### ISSUE THREAD

**Issue by RoboticsYY** [crigroup/handeye#3]
Hi @fsuarez6, I think this repo is a great work that should be well recognized to wider community. Recently I made an effort to make this repo working as a plugin to MoveIt community. Please see the [PR](https://github.com/ros-planning/moveit/pull/1559) in MoveIt. And I also ported it to ROS2 in my fork. Do you still consider releasing it to Melodic, and welcoming a porting to ROS2 PR? I would be very happy to contribute.

**Comment by fsuarez6** [comment]
Sounds like a good idea. I'll release this package and it's dependencies into Melody this weekend.
I shall add some comments to the moveit PR afterwards.

**Comment by RoboticsYY** [comment]
@fsuarez6 Thanks!

**Comment by fsuarez8** [comment]
Created the release PRs:
- baldor: https://github.com/ros/rosdistro/pull/23184
- criutils: https://github.com/ros/rosdistro/pull/23185
- handeye: https://github.com/ros/rosdistro/pull/23186

**Comment by fsuarez6** [comment]
Created the release PRs:

baldor: ros/rosdistro#23184
criutils: ros/rosdistro#23185
handeye: ros/rosdistro#23186
